project:
  type: website
language: prevodi.yml
website:
  title: "STM-HAL-vaje"
  sidebar:
    style: "docked"
    search: true
    contents:  
      - section: "Uvod"
        contents:
          - oprema.qmd
          - uvod-v-c.qmd
      - section: "GPIO"
        contents:
          - naivno.qmd
